factapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('add_customer/', views.AddCustomer.as_view(), name="add_customer"),
        path('add_invoice/', views.AddInvoiceView.as_view(), name="add_invoice"),
        path('view_invoice/<int:pk>', views.InvoiceView.as_view(), name="view_invoice"),
 path('invoice-pdf/<int:pk>/', views.get_invoice_pdf, name="invoice-pdf"),
 ]

facturation/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls)
] 

urlpatterns += i18n_patterns(
    path('', include('factapp.urls')),
)

if settings.DEBUG:

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

factapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    SEX_TYPES = [
        ('M', 'masculin'),
        ('F', 'feminin'),
    ]
    
    name = models.CharField(max_length=132)
    email = models.EmailField()
    phone = models.CharField(max_length=132)
    address = models.CharField(max_length=132)
    sex = models.CharField(max_length=1, choices=SEX_TYPES)
    age = models.CharField(max_length=12)
    city = models.CharField(max_length=32)
    zip_code = models.CharField(max_length=16)
    created_date = models.DateTimeField(auto_now_add=True)
    saved_by = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return self.name

class Facture(models.Model):
    FACTURE_TYPES = [
        ('R', 'RECU'),
        ('P', 'PROFOMAT'),
        ('F', 'FACTURE'),
    ]

    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    saved_by = models.ForeignKey(User, on_delete=models.PROTECT)
    facture_date = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    last_updated_date = models.DateTimeField(null=True, blank=True)
    paid = models.BooleanField(default=False)
    facture_type = models.CharField(max_length=1, choices=FACTURE_TYPES)
    commenter = models.TextField(max_length=1000, null=True, blank=True)

    class Meta:
        verbose_name = "Facture"
        verbose_name_plural = "Factures"

    def __str__(self):
        return f"Facture {self.facture_date} - {self.customer.name}"

    @property 
    def get_total(self):
        articles = self.article_set.all()
        total = sum(article.get_total for article in articles)
        return total

class Article(models.Model):
    facture = models.ForeignKey(Facture, on_delete=models.CASCADE)
    name = models.CharField(max_length=32)
    quantite = models.IntegerField()
    code_bar = models.CharField(max_length=320, default='')  
    prix_unite = models.DecimalField(max_digits=10000, decimal_places=2)
    total = models.DecimalField(max_digits=10000, decimal_places=2)
    
    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    @property 
    def get_total(self):
        total = self.quantite * self.prix_unite
        return total

factapp/views.py
from django.shortcuts import render,redirect
from django.views import View
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import get_template
from .decorators import *
from django.http import HttpResponse
import pdfkit
import datetime
from django.core.paginator import (Paginator,EmptyPage,PageNotAnInteger)
from django.utils.translation import gettext as _
from .utils  import get_invoice
class HomeView(LoginRequiredMixin,View):
    template_name = "index.html"

    def get(self, request, *args, **kwargs): 
        factures = Facture.objects.select_related('customer', 'saved_by').order_by('-facture_date')
          
        default_page = 1
        page = request.GET.get('page', default_page)
        items_per_page = 8
        paginator = Paginator(factures, items_per_page)
        
        try:
            factures_page = paginator.page(page)
        except PageNotAnInteger:
            factures_page = paginator.page(default_page)
        except EmptyPage:
            factures_page = paginator.page(paginator.num_pages)
            
        context = {
            'factures': factures_page
        }
   
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # Modifier 
        if request.POST.get('id_modified'):
            paid = request.POST.get('modified')
            try:
                obj = Facture.objects.get(id=request.POST.get('id_modified'))

                if paid == 'True':
                    obj.paid = True
                else:
                    obj.paid = False
                obj.save()
                messages.success(request, _("Change has been made successfully"))
            except Exception as e:
                messages.error(request, f"An error occurred: {e}")

        if request.POST.get('id_supprimer'):
                 try:
                       obj = Facture.objects.get(pk=request.POST.get('id_supprimer'))
                       obj.delete()
                       messages.success(request, _("the deletion was successful"))
                 except Exception as e:
                        messages.error(request, f"An error occurred: {e}")
       
        return redirect('home')  # Redirect to the GET view after processing the POST request

class AddCustomer(LoginRequiredMixin,View):
    template_name = "add_customer.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
      
    def post(self, request, *args, **kwargs): 
        data ={
          'name':request.POST.get('name'),
            'email':request.POST.get('email'),
              'phone':request.POST.get('phone'),
                'address':request.POST.get('address'),
                  'sex':request.POST.get('sex'),
                    'age':request.POST.get('age'),
                      'city':request.POST.get('city'),
                            'zip_code':request.POST.get('zip'),
                              'saved_by':request.user,
       }
        try :
            created=Customer.objects.create(**data)
            if  created :
                        messages.success(request,"Customer registed succefully")
            else :
                 messages.error(request,"Sorry ,please try later")           
        
        except Exception as e:
                   messages.error(request, f"Sorry, our system is detecting the following issues: {e}")
        return render(request, self.template_name)  # You can add context if needed

class AddInvoiceView(LoginRequiredMixin,View):
    template_name = "add_invoice.html"

    def get(self, request, *args, **kwargs):
        customers = Customer.objects.select_related('saved_by').all()
        articles=Article.objects.all()
        context = {
            'customers': customers,
            'articles':articles
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        try:
            customer_id = request.POST.get('customer')
            invoice_type = request.POST.get('invoice_type')
            comment = request.POST.get('comment')
            items = []

            article_ids = request.POST.getlist('article')
            quantities = request.POST.getlist('qty')
            unit_prices = request.POST.getlist('unit')
            total_amounts = request.POST.getlist('total-a')

            total = request.POST.get('total')

            invoice_object = {
                'customer_id': customer_id,
                'saved_by': request.user,
                'total': total,
                'facture_type': invoice_type, 
                'commenter': comment
            }

            invoice = Facture.objects.create(**invoice_object)

            for article_id, qty, unit_price, total_amount in zip(article_ids, quantities, unit_prices, total_amounts):
                article = Article(
                    facture=invoice,
                    name=article_id,  # You should have a proper way to fetch the name of the article
                    quantite=qty,
                    prix_unite=unit_price,
                    total=total_amount
                )
                items.append(article)

            Article.objects.bulk_create(items)

            messages.success(request, "Invoice created successfully.")
        
        except Exception as e:
            messages.error(request, f"An error occurred: {e}")

        return render(request, self.template_name)
class InvoiceView(LoginRequiredMixin,View):
         template_name = "invoice.html"
         def get(self, request, *args, **kwargs):
               pk=kwargs.get('pk')
               obj=Facture.objects.get(pk=pk)
               articles=obj.article_set.all()

               context = {
              'obj':obj,
              'articles': articles
                  }
               return render(request, self.template_name, context)
        
class InvoiceView(View):
     template_name='invoice.html'
     def get(self, request, *args, **kwargs):
               pk=kwargs.get('pk')
               context=get_invoice(pk)
               return render(request, self.template_name, context)

@superuser_required
def get_invoice_pdf(request, *args, **kwargs):
    """ generate pdf file from html file """

    pk = kwargs.get('pk')

    context = get_invoice(pk)

    context['date'] = datetime.datetime.today()

    # get html file
    template = get_template('invoice-pdf.html')

    # render html with context variables

    html = template.render(context)

    # options of pdf format 

    options = {
        'page-size': 'Letter',
        'encoding': 'UTF-8',
        "enable-local-file-access": ""
    }

    # generate pdf 

    pdf = pdfkit.from_string(html, False, options)

    response = HttpResponse(pdf, content_type='application/pdf')

    response['Content-Disposition'] = "attachement"

    return response

factapp/templates/add_customer.html
{% extends 'base.html' %}
{% block content %}

<br>
<br>
<br>

<h1 class="text-capitalize text-center mx-10 bg-dark text-white">Register new customer</h1>
<br>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="name"> Name </label>
            <input name="name" required type="text" class="form-control" id="name"
                placeholder="customer first and last name">
        </div>

        <div class="form-group col-md-4">
            <label for="email"> Email </label>
            <input name="email" required type="email" class="form-control" id="email" placeholder="customer email">
        </div>

        <div class="form-group col-md-4">
            <label for="phone"> Phone </label>
            <input name="phone" required type="number" class="form-control" id="phone"
                placeholder="customer phone number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="sex">Sex</label>
            <select name="sex" class="form-control" required id="sex">
                <option> Choose the gender .. </option>
                <option value="M">Male</option>
                <option value="F">Feminine</option>
            </select>
        </div>

        <div class="form-group col-md-6">
            <label for="age">Age</label>
            <select name="age" class="form-control" required id="age">
                <option> Choose the age range .. </option>
                <option value="0-15">0-15</option>
                <option value="0-15">15-25</option>
            </select>
        </div>

    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="addres"> Address </label>
            <input name="address" type="text" required type="text" class="form-control" id="address"
                placeholder="Customer address">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="city"> City </label>
            <input name="city" type="text" class="form-control" id="city" placeholder="customer city">
        </div>

        <div class="form-group col-md-6">
            <label for="zip"> Zip code </label>
            <input name="zip" required type="text" class="form-control" id="zip"
                placeholder="customer zip code required">
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-3"> Save</button>

</form>

<br><br><br>

{% endblock content %}

factapp/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %} 




{% block content %}
<br><br>

<div class="row">
   <a href="{% url 'add_invoice' %}" class="btn col-md-4 btn-primary">
      {% trans 'Register a new invoice' %} <span class="badge text-bg-secondary"></span>
   </a>

   <a href='#' class="col-md-4">
      <span class="badge text-bg-secondary"></span>
   </a>

   <a href="{% url 'add_customer' %}" class="btn col-md-4 btn-primary">
       {% trans ' Register a new customer' %} <span class="badge text-bg-secondary"></span>
   </a>

</div>

<br> <br>

<div class="form-group ">
   <input id="search" class="form-control" type="text" placeholder={% trans 'Search....' %}>
</div>

<div>
   <table class="table table-striped-columns">
      <thead>
         <tr>
            <th scope="col">#</th>
            <th scope="col"> {% trans ' Customer name' %}</th>
            <th scope="col">{% trans ' Date' %}</th>
            <th scope="col">{% trans ' Total' %}</th>
            <th scope="col">{% trans ' Paid' %}</th>
            <th scope="col">{% trans 'Type of Invoice' %}</th>
            <th scope="col">{% trans 'Action' %}</th>
         </tr>
      </thead>
      <tbody id="myTable">
         {% if factures %}
         {% for facture in factures %}
            <tr>
              <td>{{forloop.counter}}</td>
            <td>{{facture.customer.name}}</td>
            <td>{{facture.facture_date}}</td>
            <td>{{ facture.get_total }} DA</td>
            <td>
               {% if facture.paid %}
               <img src="{% static 'images/icon-yes.svg' %}" alt="True">
               {% else %}
               <img src="{% static 'images/icon-no.svg' %}" alt="False">
               {% endif %}
            </td>
            <td>{{facture.get_facture_type_display }}</td>
            <td>
               <a href="{% url 'view_invoice' pk=facture.pk%}"title="Detail" class="badge text-white bg-success">{% trans 'View' %}</a>

               <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer"
                  class="badge text-white bg-danger" title="Supprimer" data-id="{{ facture.pk }}"
                  data-customer="{{facture.customer.name}}">{% trans 'Delete' %}
               </button>

               <button id="btn-invoice-mod" type="button" data-toggle="modal" title="Modifier" data-target="#modifier"
                  data-id="{{facture.pk}}" data-customer="{{facture.customer.name}}"
                  class="badge text-dark bg-warning"> {% trans 'Modify'  %}
               </button>
            </td>
         </tr>

         {% endfor %}

         {% if factures.has_other_pages %}

         <div class="btn-group" role="group" aria-label="Item pagination">

            {% if factures.has_previous %}

            <a href="?page={{ factures.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>

            {% endif %}

            {% for page_number in factures.paginator.page_range %}

               {% if factrues.number == page_number %}

                  <button class="btn btn-outline-primary active">
                     <span> {{page_number}} <span class="sr-only">(current)</span></span>

                  </button>

                  {% else %}
                     <a href="?page={{page_number}}" class="btn btn-outline-primary">
                        {{ page_number }}
                     </a>


               {% endif %}   

            {% endfor %}

            {% if invoices.has_next %}

               <a href="?page={{ factures.next_page_number }}" class="btn btn-outline-primary">&laquo;</a>

            {% endif %}



         </div>

         {% endif %}

         {% else %}
         
         <p class="text-center text-white">No invoice found.</p>
         {% endif %}


      </tbody>

   </table>
</div>

<!-- Modal modifier -->
<div class="modal fade" id="modifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark text-center" id="exampleModalLabel">Modification</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="post">
            {% csrf_token %}
            <div class="modal-body">

               <input name="id_modified" type="hidden" id="id_modified">

               <label id="label_id" class="text-dark checkbox-inline"> <strong id="strong_id"> This bill has been paid?</strong></label>

               <input type="radio" id="html" name="modified" value="True">
               <label class="text-white bg-primary" for="html">Yes</label>

               <input type="radio" id="css" name="modified" value="False">
               <label class="text-white bg-danger" for="css">No</label><br>

            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <button type="submit" class="btn btn-primary">Save</button>
            </div>
         </form>
      </div>
   </div>
</div>
<!-- end modal-->

<!-- Modal suppression -->
<div class="modal fade" id="supprimer" tabindex="-1" role="dialog" aria-labelledby="sexampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark" id="sexampleModalLabel">Delete Invoice</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form method="post">
               {% csrf_token %}
               <input name="id_supprimer" type="hidden" id="id_supprimer">
               <label id="label_id_s" class="text-dark checkbox-inline"> <strong id="strong_id_s">Are you sure you want to delete the invoice  ?</strong></label>

               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
               </div>
            </form>
         </div>

      </div>
   </div>
</div>
<!-- end modal-->

<br><br>

<script type="text/javascript">

   // modification

   $(document).on('click', '#btn-invoice-mod', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_modified').val(invoice_id);

   })

   // deleting of invoice

   $(document).on('click', '#btn-invoice-sup', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_supprimer').val(invoice_id);

   })



</script>


<script>

   $(document).ready(function(){
      $("#search").on("keyup", function(){
         var value = $(this).val().toLowerCase();
         $("#myTable tr").filter(function(){
            $(this).toggle($(this).text().toLocaleLowerCase().indexOf(value)>-1)
         });
      });
   });

</script>



{% endblock %}

factapp/templates/invoice-pdf.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
  integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="/static/invoice.css">
<!-- jquery -->
<style>
    /* Styling the invoice container */
.invoice-container {
    border: 1px solid #ccc;
    padding: 20px;
}

/* Styling the invoice header */
.invoice-header {
    background-color: #f0f0f0;
    padding: 10px;
}

/* Styling the invoice body */
.invoice-body {
    margin-top: 20px;
}

/* Styling the invoice table */
.custom-table {
    width: 100%;
    border-collapse: collapse;
}

/* Styling table headers */
.custom-table th {
    background-color: #f0f0f0;
    text-align: left;
    padding: 10px;
}

/* Styling table rows */
.custom-table td {
    border: 1px solid #ccc;
    padding: 10px;
}

/* Styling the invoice footer */
.invoice-footer {
    margin-top: 20px;
    text-align: center;
    font-style: italic;
}
</style>
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM="
  crossorigin="anonymous"></script>
    <title>Facture</title>
</head>
<body>
    <div class="container" >
        <div class="row gutters">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="invoice-container">
                            <div class="invoice-header">
                                <!-- Row start -->
                                <div class="row gutters ml-3">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                        <a href="" class="invoice-logo">
                                            Amine Shop
                                        </a>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6  ">
                                        <address class="text-right">
                                            Amine shop ,boulvard des lions <br>
                                            Algerie, Oran<br>
                                            31000
                                        </address>
                                    </div>
                                </div>
                                <!-- Row end -->
        
                                <!-- Row start -->
                                <div class="row gutters mt-3">
                                    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                                        <div class="invoice-details mr-3">
                                            <address>
                                                {{obj.customer.name}}<br>
                                                {{obj.customer.address}}, {{obj.customer.city}},Algerie
                                        </div>
                                    </div>
                                    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                                        <div class="invoice-details">
                                            <div class="invoice-num">
                                                <div>{{obj.get_facture_type_display}} - #00{{obj.id}}</div>
                                                <div>{{obj.facture_date}}</div>
                                            </div>
                                        </div>													
                                    </div>
                                </div>
                                <!-- Row end -->
        
                            </div>
        
                            <div class="invoice-body">
        
                                <!-- Row start -->
                                <div class="row gutters">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="table-responsive">
                                            <table class="table custom-table m-0">
                                                <thead>
                                                    <tr>
                                                        <th>Items</th>
                                                        <th>Product ID</th>
                                                        <th>Quantities</th>
                                                        <th>Unit Price</th>
                                                        <th>Subtotal</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                  {% for article in articles %}  
                                                  
                                                    <tr>
    
                                                       
    
                                                        <td>
                                                            {{ article.name }}
                                                            
                                                        </td>
    
                                                        <td>
                                                            {{ article.id }}
                                                            
                                                        </td>
    
                                                        <td>
                                                            {{ article.quantite }}
                                                            
                                                        </td>
    
                                                        <td>
                                                            {{ article.prix_unite }}
                                                            DA
                                                        </td>
    
                                                        <td>
                                                            {{ article.get_total }}
                                                            DA
                                                        </td>
    
                                                        
                                                        
                                                    </tr>
                                                   {% endfor %} 
                                                    
                                                    
                                                    <tr>
                                                        <td>Comment: {{obj.comments}}</td>
                                                        <td colspan="2">
                                                            <p>
                                                                Subtotal<br>
                                                                Shipment &amp; Handling<br>
                                                                Tax<br>
                                                            </p>
                                                            <h5 class="text-success"><strong>Total</strong></h5>
                                                        </td>			
                                                        <td>
                                                            <p>
                                                                {{obj.get_total}} DA<br>
                                                                00.00 DA<br>
                                                                00.00 DA<br>
                                                            </p>
                                                            <h5 class="text-success"><strong>{{obj.get_total}} Da </strong></h5>
                                                        </td>
                                                        <td> 
                                                                PAID:                    
    
                                                            {% if obj.paid  %}
   <strong>YES</strong> 
                                                             
       {% else %}
       <strong>NO</strong>
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <!-- Row end -->
        
                            </div>
        
                            <div class="invoice-footer">
                                Thank you for your purchase {{date}}
                            </div>
        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>